name: building and testing iNotebook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - run: echo "checking out repository code"
        
      - name: checck code
        uses: actions/checkout@v3
      - name: setting node version
        uses: actions/setup-node@v16.17.0
      - name: Listing files in the directory
        run: ls
      - name: Installing dependencies
        run:  npm install
        
      - name: testing the actual file
        run:  npm run both
